# Generated by Django 4.2.3 on 2023-07-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0006_alter_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qappapproval',
            name='id',
        ),
        migrations.AlterField(
            model_name='qappapproval',
            name='qapp',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qapp_builder.qapp'),
        ),
    ]
