# Generated by Django 4.2.3 on 2023-07-20 15:51

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scifinder', '0012_alter_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='C:\\git\\projects\\epa\\datasearch\\DataSearch\\DataSearch/media\\uploads'), upload_to=constants.utils.get_scifinder_storage_path),
        ),
    ]
